{{- range $serviceName, $service := .Values.services }}
{{- if $service.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $service.fullName }}-secret
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "circleguard.serviceLabels" (dict "root" $ "serviceName" $serviceName "service" $service) | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := $service.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
