{{- range $serviceName, $service := .Values.services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $service.fullName }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "circleguard.serviceLabels" (dict "root" $ "serviceName" $serviceName "service" $service) | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
