global:
  environment: prod
  springProfilesActive: prod
  ingress:
    host: circleguard.edu

defaults:
  replicas: 3

services:
  auth-service:
    image:
      tag: prod
  identity-service:
    image:
      tag: prod
  promotion-service:
    image:
      tag: prod
  notification-service:
    image:
      tag: prod
  form-service:
    image:
      tag: prod
  file-service:
    image:
      tag: prod
  gateway-service:
    image:
      tag: prod
  dashboard-service:
    image:
      tag: prod
